version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ap-south-1)
      - cd serviceB/


  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t test2 .
      - docker tag test2:latest 775664058672.dkr.ecr.ap-south-1.amazonaws.com/test2:V.${CODEBUILD_BUILD_ID##*:}


  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 775664058672.dkr.ecr.ap-south-1.amazonaws.com/test2:V.${CODEBUILD_BUILD_ID##*:}
